config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pins do
    member do
      put "like", to: "pins#upvote"
    end
  end
  root "pins#index"

end

app/models/pin.rb
class Pin < ActiveRecord::Base
    acts_as_votable
    belongs_to :user
    
    has_attached_file :image, styles: { medium: "300x300>" }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
    before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote]
    before_action :authenticate_user!, except: [:index, :show]
    def index
        @pins = Pin.all.order("created_at DESC")
    end
    def show
        
    end
    def new
        @pin = current_user.pins.build
    end
    def create
        @pin = current_user.pins.build(pin_params)
        
        if @pin.save
            redirect_to @pin, notice: "Your Pin was created!"
        else render "new"
        end
    end
    
    def edit
    end
    
    def update
        if @pin.update(pin_params)
                redirect_to @pin, notice: "Pin was updated successfully!"
        else
            render 'edit'
        end
    end
    
    def destroy
        @pin.destroy
        redirect_to root_path
    end
    
    def upvote
        @pin.upvote_by current_user
        redirect_to :back
    end
    
    
    private
    
    def pin_params
        params.require(:pin).permit(:title, :description, :image)
    end
    
    def find_pin
        @pin = Pin.find(params[:id])
    end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_nav.html.erb
<% if !user_signed_in? %>
  <%= render '/layouts/nav_guest' %>
<% else %>
<%= render 'layouts/nav_user' %>
<% end %>

app/views/layouts/_nav_guest.html.erb
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<nav class="navbar navbar-default">
  <div class="container-fluid container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="pin-logo"><%= link_to "Pinit", root_path %></li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
            <li><%= link_to('Sign Up', new_user_registration_path) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to('Log In', new_user_session_path) %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_nav_user.html.erb
<a name="top"></a>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<nav class="navbar navbar-default">
  <div class="container-fluid container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav pin-logo">
        <li><%= link_to "Pinit", root_path %></li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "New Pin", new_pin_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Account", edit_user_registration_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html></html>
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Pinit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render '/layouts/nav' %>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert alert-info" %>
    <% end %>
    <%= yield %>
  </div>
</body>

app/views/pins/_form.html.erb
<%= simple_form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="errors">
      <h2>
        <%= pluralize(@pin.errors.count, "error") %>
        prevented this Pin from saving
      </h2>
      <ul>
        <% @pin.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.input :image, input_html: { class: 'btn btn-primary' }, label: 'Upload Image' %>
  </div>
  <div class="form-group">
    <%= f.input :title, input_html: { class: 'form-control' }	 %>
  </div>
  <div class="form-group">
    <%= f.input :description, input_html: { class: 'form-control' } %>
  </div>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/pins/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <h1>Edit Pin</h1>
  <%= image_tag @pin.image.url(:medium) %>
  <%= render 'form' %>
  <%= link_to "Cancel", pin_path %>
</div>

app/views/pins/index.html.erb
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<div class="transitions-enabled" id="pins">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= link_to (image_tag pin.image.url), pin %>
      <div class="panel-body">
        <h2>
          <%= link_to pin.title, pin %>
        </h2>
        <p class="user"></p>
        Submitted by
        <%= pin.user.email %>
      </div>
    </div>
  <% end %>
</div>

app/views/pins/new.html.erb
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<div class="col-md-6 col-md-offset-3">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>New Form</h1>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/pins/show.html.erb
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<div class="row" id="pin_show">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading pin_image">
        <%= image_tag @pin.image.url %>
      </div>
      <div class="panel-body">
        <h1>
          <%= @pin.title %>
        </h1>
        <p class="description">
          <%= @pin.description %>
        </p>
        <p></p>
        Submitted by 
        <%= @pin.user.email %>
      </div>
      <div class="panel-footer">
        <div class="row">
          <div class="col-md-6">
            <p class="user"></p>
            Submitted by 
            <%= @pin.user.email %>
          </div>
          <div class="col md-6">
            <div class="btn-group pull-right">
              <%= link_to like_pin_path(@pin), method: :put, class: "btn btn-default" do %>
                <span class="glyphicon glyphicon-heart">
                  <%= @pin.get_upvotes.size %>
                </span>
              <% end %>
              <% if user_signed_in? %>
                <%= link_to "Edit", edit_pin_path, class: "btn btn-default" %>
                <%= link_to "Delete", pin_path, method: :delete, data: { confirm: "Are you sure you want to delete this pin?" }, class: "btn btn-primary" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

              
              
              